#!/bin/sh

#
#  Copyright (c) 2016 Wind River Systems, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at:
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#

/home/root/bluetoothstartup.sh
/usr/bin/node /home/root/enable_serial_edison.js&
sleep 3
/usr/bin/python /home/root/arduino_edison.py > /home/root/arduino_edison.log &

